name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2025-9-02"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow-db"
database_id = "5aac4ee1-0bbc-471f-a88c-b652e6b21eef"
